name: 'Remove artifacts'
author: 'c-hive'
description: ''
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  age:
    description: 'Artifacts older than this will be deleted (e.g. "2 months", "1 day"). Parsed by moment.'
    required: true
