name: CI

on: [push]

jobs:
  run-action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-node_modules-${{ hashFiles('**//package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}--
    - name: Install NPM dependencies
      run: npm install
    - name: Run action
      uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
